[WIP] feat(api): Generate a blake2b-256 hash of a given binary buffer.
input-output-hk/hermes pull request #120
Opened 2024-02-08 07:57 UTC by bkioshn

# Description

Generate a blake2b-256 hash of a given binary buffer.

## Related Issue(s)

Closes #98 

## Description of Changes

TODO

## Related Pull Requests

TODO

## Please confirm the following checks

* [ ] My code follows the style guidelines of this project
* [ ] I have performed a self-review of my code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have made corresponding changes to the documentation
* [ ] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream module

2024-02-08 16:37 UTC, Mr-Leshiy commented on hermes/bin/Cargo.toml
> +blake2.workspace = { workspace = true }
```suggestion
blake2 = { workspace = true }
```

2024-02-08 16:37 UTC, Mr-Leshiy commented on hermes/bin/Cargo.toml
> +hex-literal.workspace = { workspace = true }
```suggestion
hex-literal = { workspace = true }
```

2024-02-08 16:37 UTC, Mr-Leshiy commented on hermes/bin/src/runtime/host/hermes/hash/mod.rs
> +        let mut v = Blake2bVarCore::new_with_params(salt, persona, key_size, output_size);
I would rather move all this code under some free function `blake2b(...)` and call it inside `HermesState::blake2b`.
So the unit test would be much simpler and will cost for us nothing, you will not need to setup a `Hermes` instance,  wasm module etc.

And to proper test how it is working under the WASM context, we will would rather write integration tests, but it is another story.

2024-02-13 15:58 UTC, stevenj reviewed
I know i suggested this blake2 crate, but i see the problems it causes by not being a good match for our requirements.
Have a look at https://crates.io/crates/blake2b_simd
Which might be a better fit.

2024-02-14 07:20 UTC, apskhem commented on hermes/bin/src/runtime/host/hermes/hash/mod.rs
> +        }
```suggestion
        blake2bmac_impl(&buf, outlen, &key, salt, persona)
            .map(Ok)
            .map_err(Into::into)
```

2024-02-14 08:00 UTC, bkioshn commented on hermes/bin/src/runtime/host/hermes/hash/mod.rs
> +    }
Pattern matching doesn't work here. Will change the crate

2024-02-14 08:02 UTC, bkioshn commented on hermes/bin/src/runtime/host/hermes/hash/mod.rs
> +        }
Thank you, much cleaner

2024-02-14 09:25 UTC, Mr-Leshiy requested changes

2024-02-14 09:25 UTC, Mr-Leshiy commented on hermes/bin/src/runtime/host/hermes/hash/blake2b.rs
> +    let outlen = outlen.unwrap_or(64) as usize;
```suggestion
    let outlen: usize = outlen.unwrap_or(64).into();
```

2024-02-14 09:25 UTC, Mr-Leshiy commented on hermes/bin/src/runtime/host/hermes/hash/blake2b.rs
> +    let outlen = outlen.unwrap_or(64) as usize;
```suggestion
    let outlen: usize = outlen.unwrap_or(64).into();
```

2024-02-14 09:25 UTC, Mr-Leshiy commented on hermes/bin/src/runtime/host/hermes/hash/blake2b.rs
> +    return Ok(Bstr::from(hash.as_bytes()));
```suggestion
    return Ok(hash.as_bytes().into());
```

2024-02-14 09:25 UTC, Mr-Leshiy commented on hermes/bin/src/runtime/host/hermes/hash/blake2b.rs
> +    return Ok(Bstr::from(hash.as_bytes()));
```suggestion
    return Ok(hash.as_bytes().into());
```

2024-02-14 09:25 UTC, Mr-Leshiy commented on hermes/bin/src/runtime/host/hermes/hash/blake2b.rs
> +/// Implementation of blake2b given a buffer and outlen.
Describe as a part of the documentation what probable errors could occur.

2024-02-14 09:25 UTC, Mr-Leshiy commented on hermes/bin/src/runtime/host/hermes/hash/blake2b.rs
> +/// Implementation of blake2bmac given a buffer, outlen, key, salt, and persona.
Describe as a part of the documentation what probable errors could occur.

2024-02-14 09:25 UTC, Mr-Leshiy commented on hermes/bin/src/runtime/host/hermes/hash/mod.rs
> +        blake2b::blake2b_impl(&buf, outlen)
I am not sure that this is a correct conversion which you are doing here.
It seems like you are converting a `Errno` to the `wasmtime::Error` which is not correct for this place.
I think here you should return the following.
```
Ok( blake2b::blake2b_impl(&buf, outlen))
```

2024-02-14 09:25 UTC, Mr-Leshiy commented on hermes/bin/src/runtime/host/hermes/hash/mod.rs
> +        blake2b::blake2bmac_impl(&buf, outlen, &key, salt, personal)
Same as above

2024-02-14 21:08 UTC, Mr-Leshiy submitted a review, later dismissed
Besides few comments LGTM

2024-02-14 21:08 UTC, Mr-Leshiy commented on hermes/bin/src/runtime/host/hermes/hash/blake2b.rs
> +/// **Parameters**
Update the format to the following:
```
# Arguments
- ...

# Errors
- ...
```
It is a common way for Rust how to describe such sections https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#commonly-used-sections.

2024-02-14 21:08 UTC, Mr-Leshiy commented on hermes/bin/src/runtime/host/hermes/hash/blake2b.rs
> +/// **Parameters**
same

2024-02-15 08:00 UTC, stevenj approved these changes
Looks great.

2024-02-15 09:24 UTC, merged