[WIP] feat(rust): Time Module Implementation
input-output-hk/hermes pull request #142
Opened 2024-02-21 04:07 UTC by saibatizoku

# Description

Thanks for contributing to the project!
Please fill out this template to help us review your changes.

## Related Issue(s)

List the issue numbers related to this pull request.

Closes #88 

## Description of Changes

Provide a clear and concise description of what the pull request changes.

## Breaking Changes

Describe any breaking changes and the impact.

## Screenshots

If applicable, add screenshots to help explain your changes.

## Related Pull Requests

If applicable, list any related pull requests.

> e.g., #123, #456

## Please confirm the following checks

* [ ] My code follows the style guidelines of this project
* [ ] I have performed a self-review of my code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have made corresponding changes to the documentation
* [ ] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream module

2024-02-21 15:03 UTC, stevenj requested changes
Also needs the wasi/clock APIs as these are part of the Time utilities for Hermes.

2024-02-22 15:49 UTC, stevenj reviewed
Wall clock can just be implemented using:
https://doc.rust-lang.org/std/time/struct.SystemTime.html
Use the constant `UNIX_EPOCH` as the base for wall clock.
Then get `elapsed().as_nanos()` which will return a u128 which can be mapped into the sec/nanosec of the wasm return type.

Again, resolution here would always be nanosceonds.

2024-02-22 15:49 UTC, stevenj commented on hermes/bin/src/runtime_extensions/wasi/clocks/monotonic/host.rs
> +        now_impl()
I would use this: https://doc.rust-lang.org/std/time/struct.Instant.html

At start of world, get a GLOBAL `base` "instant" now().
Then for every call, just return `base.elapsed().as_nanos()`

2024-02-22 15:49 UTC, stevenj commented on hermes/bin/src/runtime_extensions/wasi/clocks/monotonic/host.rs
> +        resolution_impl()
Because of the above, this is always nanoseconds, and needs not be any other value.

2024-03-12 06:25 UTC, stevenj requested changes

2024-03-13 12:26 UTC, stevenj approved these changes
LGTM

2024-03-13 18:20 UTC, FelipeRosa approved these changes
LGTM

2024-03-13 18:20 UTC, merged