feat: Add cli functionality for hermes, and run command with loading a HermesApp
input-output-hk/hermes pull request #216
Opened 2024-04-25 08:48 UTC by Mr-Leshiy

# Description

Added a cli functionality for hermes with a simple `run` command which loads and runs a HermesApp

2024-04-25 09:24 UTC, minikin requested changes
Let's add/update README on how to use it.

2024-05-14 02:15 UTC, stevenj commented
This PR conflates multiple things.

1. Why did you remove Build Info which was specifically added at my request?  I wan't all our applications to report how they are built, version etc.  So why was it removed?
2. Why have we refactored all of the logging?  We should not be just changing behaviour without it being discussed.  Logging was done how it was because its a step towards a proper logging solution, this change does not advance that solution.  We should not be doing work on issues that are not issues.  The proper solution is to add a subscriber for all log messages, which categorises them and stores them for reporting through a future UI OR sends them to stdout/stderr.  These changes don't go in that direction that I can see and so are wasdted effort.  This is why we should not be adding things which are not scoped and discussed.
3. Why do we need a "run" cli command?  Hermes should just run if its not given any other option, I also want to NOT add tons of CLI arguments and options, we have already discussed this.  When we allow hermes to do other things, they can be commands with options, but running the hermes executable itself should never need "run".

So, I wonder why any of this was done?  

At the very least these three changes should be in their own PR.  But that said, changes 1 and 2 are not necessary and revert work already done intentionally, so should be part of any PR.

2024-05-14 02:15 UTC, stevenj requested changes
See comment i left

2024-05-16 10:28 UTC, Mr-Leshiy commented on hermes/crates/cbork/cddl-parser/Cargo.toml
> -derive_more =  "0.99.17"
I didn't change it that way, they are in their own workspace.

2024-05-21 08:57 UTC, stevenj requested changes

2024-05-21 09:56 UTC, stevenj approved these changes

2024-05-21 10:17 UTC, minikin approved these changes

2024-05-21 10:17 UTC, merged