feat: Add basic hdf5 compression
input-output-hk/hermes pull request #240
Opened 2024-05-24 10:00 UTC by Mr-Leshiy

# Description

Added basic compression implementation for hdf5 packages.

## Related Issue(s)

#237

2024-05-27 07:45 UTC, stevenj requested changes
My only concern is in the test file.
I think we can use the repo itself to give us an equivalent test data set.

2024-05-27 07:45 UTC, stevenj commented on hermes/bin/src/packaging/large.json
Rather than adding a large test file to the git repo,  why don't we just store all the files in the project from the repo root?
This is also a large set of files of variable types, and you already had a function to store a directory into the HDF5 file.
As its mostly src code, it should have very good compression characteristics.

2024-05-27 08:01 UTC, Mr-Leshiy commented on hermes/bin/src/packaging/large.json
yea, will try that

2024-05-27 08:19 UTC, Mr-Leshiy commented on hermes/bin/src/packaging/large.json
updated

2024-05-27 12:27 UTC, stevenj submitted a review, later dismissed
LGTM

2024-05-31 07:40 UTC, stevenj approved these changes

2024-05-31 07:40 UTC, merged